services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employee -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:18
    container_name: postgres_test_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: employee_test_db
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employee -d employee_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data: